'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Reverse_Tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonFormatUser_ImageOptions_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonFormatUser.ImageOptions.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property C4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("C4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cyber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cyber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dd() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dd", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Erase22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erase22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Erasefrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erasefrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Factory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Format22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Format22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoapple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoapple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoasus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoasus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logochipmediatek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logochipmediatek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logochipqualcomm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logochipqualcomm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logochipspreadtrum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logochipspreadtrum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logohuawei() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logohuawei", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoinfinix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoinfinix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoireverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoireverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logomediatek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logomediatek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logomeizu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logomeizu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logomi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logomi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logonokia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logonokia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logooppo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logooppo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoqualcomm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoqualcomm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logorealme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logorealme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logosamsung() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logosamsung", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logospreadtrum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logospreadtrum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logovivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logovivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General settings creat command
        '''General Command exec
        '''General Command ::LoadDA
        '''General Command ::LoadScatterFile
        '''General Command ::LoadRoms
        '''load roms in rom list
        '''General Command ::LoadAuthFile
        '''General Command ::LoadCertFile
        '''General command exec done!
        '''Connection create done!
        '''Command (0)::Execute
        '''Connecting to BROM...
        '''Scanning USB port...
        '''Search usb, timeout set as 120000 ms
        '''USB port detected
        '''BROM connected
        '''Downloading &amp; Connecting to DA...
        '''connect DA end stage: 2, enable DRAM in 1st DA: 0
        '''COM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property logs() As String
            Get
                Return ResourceManager.GetString("logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WRITE TO PARTITION.
        '''</summary>
        Friend ReadOnly Property logs1() As String
            Get
                Return ResourceManager.GetString("logs1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MiCloud22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MiCloud22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property miremof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miremof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenLock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenLock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to process.exe
        '''python3.dll
        '''python38.dll
        '''vcruntime140.dll.
        '''</summary>
        Friend ReadOnly Property process() As String
            Get
                Return ResourceManager.GetString("process", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Readinfo22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Readinfo22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Safe22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safe22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Safe22px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safe22px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property safeformat_emmc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("safeformat_emmc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property safeformat_ufs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("safeformat_ufs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save22px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save22px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property skip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("skip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashToolLib.dll
        '''FlashToolLib.v1.dll
        '''FlashtoollibEx.dll
        '''libeay32.dll
        '''Memorymodule.dll
        '''MobileDevice104.dll
        '''phonon4.dll
        '''platform.xml
        '''QMSL_MSVC10R.dll
        '''QtCore4.dll
        '''QtGui4.dll
        '''QtNetwork4.dll
        '''QtWebKit4.dll
        '''QtXmlPatterns4.dll
        '''SLA_Challenge.dll
        '''storage_setting.xml
        '''usb_setting.xml.
        '''</summary>
        Friend ReadOnly Property Spdata() As String
            Get
                Return ResourceManager.GetString("Spdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stop_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stop30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
