Imports System
Imports System.Resources

Namespace Reverse_Tool


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Reverse_tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property C4 As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("C4", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        Friend Shared ReadOnly Property skip As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("skip", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        Friend Shared ReadOnly Property safeformat_emmc As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("safeformat_emmc", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        Friend Shared ReadOnly Property safeformat_ufs As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("safeformat_ufs", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property cyber As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cyber", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Erase22 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erase22", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Erasefrp As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erasefrp", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Factory As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factory", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Format22 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Format22", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to General settings creat command
        ''' General Command exec
        ''' General Command ::LoadDA
        ''' General Command ::LoadScatterFile
        ''' General Command ::LoadRoms
        ''' load roms in rom list
        ''' General Command ::LoadAuthFile
        ''' General Command ::LoadCertFile
        ''' General command exec done!
        ''' Connection create done!
        ''' Command (0)::Execute
        ''' Connecting to BROM...
        ''' Scanning USB port...
        ''' Search usb, timeout set as 120000 ms
        ''' USB port detected
        ''' BROM connected
        ''' Downloading &amp; Connecting to DA...
        ''' connect DA end stage: 2, enable DRAM in 1st DA: 0
        ''' COM [rest of string was truncated]&quot;;.
        ''' </summary>
        Friend Shared ReadOnly Property logs As String
            Get
                Return ResourceManager.GetString("logs", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to WRITE TO PARTITION.
        ''' </summary>
        Friend Shared ReadOnly Property logs1 As String
            Get
                Return ResourceManager.GetString("logs1", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property MiCloud22 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MiCloud22", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property miremof As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miremof", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property OpenLock As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenLock", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to process.exe
        ''' python3.dll
        ''' python38.dll
        ''' vcruntime140.dll.
        ''' </summary>
        Friend Shared ReadOnly Property process As String
            Get
                Return ResourceManager.GetString("process", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Readinfo22 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Readinfo22", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Safe22 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safe22", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Safe22px As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safe22px", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Save22 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save22", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Save22px As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save22px", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to FlashToolLib.dll
        ''' FlashToolLib.v1.dll
        ''' FlashtoollibEx.dll
        ''' libeay32.dll
        ''' Memorymodule.dll
        ''' MobileDevice104.dll
        ''' phonon4.dll
        ''' platform.xml
        ''' QMSL_MSVC10R.dll
        ''' QtCore4.dll
        ''' QtGui4.dll
        ''' QtNetwork4.dll
        ''' QtWebKit4.dll
        ''' QtXmlPatterns4.dll
        ''' SLA_Challenge.dll
        ''' storage_setting.xml
        ''' usb_setting.xml.
        ''' </summary>
        Friend Shared ReadOnly Property Spdata As String
            Get
                Return ResourceManager.GetString("Spdata", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Stop_30 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop_30", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Stop30 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop30", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logoasus As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoasus", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logochipmediatek As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logochipmediatek", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logochipqualcomm As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logochipqualcomm", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logohuawei As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logohuawei", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logoinfinix As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoinfinix", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logomediatek As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logomediatek", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logomeizu As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logomeizu", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logomi As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logomi", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logonokia As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logonokia", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logooppo As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logooppo", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logoqualcomm As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoqualcomm", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logorealme As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logorealme", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logosamsung As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logosamsung", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logovivo As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logovivo", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logospreadtrum As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logospreadtrum", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
        Friend Shared ReadOnly Property logoapple As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoapple", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
